package quake;

@:build(quake.EdictVarOfsMacro.build())
abstract EdictVarOfs<@:const TViewField>(Int) to Int {
    @f var modelindex = 0; // float
    @f var absmin = 1; // vec3
    @f var absmin1 = 2;
    @f var absmin2 = 3;
    @f var absmax = 4; // vec3
    @f var absmax1 = 5;
    @f var absmax2 = 6;
    @f var ltime = 7; // float
    @f var movetype = 8; // float
    @f var solid = 9; // float
    @f var origin = 10; // vec3
    @f var origin1 = 11;
    @f var origin2 = 12;
    @f var oldorigin = 13; // vec3
    @f var oldorigin1 = 14;
    @f var oldorigin2 = 15;
    @f var velocity = 16; // vec3
    @f var velocity1 = 17;
    @f var velocity2 = 18;
    @f var angles = 19; // vec3
    @f var angles1 = 20;
    @f var angles2 = 21;
    @f var avelocity = 22; // vec3
    @f var avelocity1 = 23;
    @f var avelocity2 = 24;
    @f var punchangle = 25; // vec3
    @f var punchangle1 = 26;
    @f var punchangle2 = 27;
    @f var classname = 28; // string
    @f var model = 29; // string
    @f var frame = 30; // float
    @f var skin = 31; // float
    @f var effects = 32; // float
    @f var mins = 33; // vec3
    @f var mins1 = 34;
    @f var mins2 = 35;
    @f var maxs = 36; // vec3
    @f var maxs1 = 37;
    @f var maxs2 = 38;
    @f var size = 39; // vec3
    @f var size1 = 40;
    @f var size2 = 41;
    @f var touch = 42; // func
    @f var use = 43; // func
    @f var think = 44; // func
    @f var blocked = 45; // func
    @f var nextthink = 46; // float
    @f var groundentity = 47; // edict
    @f var health = 48; // float
    @f var frags = 49; // float
    @f var weapon = 50; // float
    @f var weaponmodel = 51; // string
    @f var weaponframe = 52; // float
    @f var currentammo = 53; // float
    @f var ammo_shells = 54; // float
    @f var ammo_nails = 55; // float
    @f var ammo_rockets = 56; // float
    @f var ammo_cells = 57; // float
    @f var items = 58; // float
    @f var takedamage = 59; // float
    @f var chain = 60; // edict
    @f var deadflag = 61; // float
    @f var view_ofs = 62; // vec3
    @f var view_ofs1 = 63;
    @f var view_ofs2 = 64;
    @f var button0 = 65; // float
    @f var button1 = 66; // float
    @f var button2 = 67; // float
    @f var impulse = 68; // float
    @f var fixangle = 69; // float
    @f var v_angle = 70; // vec3
    @f var v_angle1 = 71;
    @f var v_angle2 = 72;
    @f var idealpitch = 73; // float
    @f var netname = 74; // string
    @f var enemy = 75; // edict
    @f var flags = 76; // float
    @f var colormap = 77; // float
    @f var team = 78; // float
    @f var max_health = 79; // float
    @f var teleport_time = 80; // float
    @f var armortype = 81; // float
    @f var armorvalue = 82; // float
    @f var waterlevel = 83; // float
    @f var watertype = 84; // float
    @f var ideal_yaw = 85; // float
    @f var yaw_speed = 86; // float
    @f var aiment = 87; // edict
    @f var goalentity = 88; // edict
    @f var spawnflags = 89; // float
    @f var target = 90; // string
    @f var targetname = 91; // string
    @f var dmg_take = 92; // float
    @f var dmg_save = 93; // float
    @f var dmg_inflictor = 94; // edict
    @f var owner = 95; // edict
    @f var movedir = 96; // vec3
    @f var movedir1 = 97;
    @f var movedir2 = 98;
    @f var message = 99; // string
    @f var sounds = 100; // float
    @f var noise = 101; // string
    @f var noise1 = 102; // string
    @f var noise2 = 103; // string
    @f var noise3 = 104; // string

    @f var ammo_shells1 = null;
    @f var ammo_nails1 = null;
    @f var ammo_lava_nails = null;
    @f var ammo_rockets1 = null;
    @f var ammo_multi_rockets = null;
    @f var ammo_cells1 = null;
    @f var ammo_plasma = null;
    @f var gravity = null;
    @f var items2 = null;
}
