package quake;

@:publicFields
class EdictVarOfs {
    @f static inline var modelindex = 0; // float
    @f static inline var absmin = 1; // vec3
    @f static inline var absmin1 = 2;
    @f static inline var absmin2 = 3;
    @f static inline var absmax = 4; // vec3
    @f static inline var absmax1 = 5;
    @f static inline var absmax2 = 6;
    @f static inline var ltime = 7; // float
    @f static inline var movetype = 8; // float
    @f static inline var solid = 9; // float
    @f static inline var origin = 10; // vec3
    @f static inline var origin1 = 11;
    @f static inline var origin2 = 12;
    @f static inline var oldorigin = 13; // vec3
    @f static inline var oldorigin1 = 14;
    @f static inline var oldorigin2 = 15;
    @f static inline var velocity = 16; // vec3
    @f static inline var velocity1 = 17;
    @f static inline var velocity2 = 18;
    @f static inline var angles = 19; // vec3
    @f static inline var angles1 = 20;
    @f static inline var angles2 = 21;
    @f static inline var avelocity = 22; // vec3
    @f static inline var avelocity1 = 23;
    @f static inline var avelocity2 = 24;
    @f static inline var punchangle = 25; // vec3
    @f static inline var punchangle1 = 26;
    @f static inline var punchangle2 = 27;
    @i static inline var classname = 28; // string
    @i static inline var model = 29; // string
    @f static inline var frame = 30; // float
    @f static inline var skin = 31; // float
    @f static inline var effects = 32; // float
    @f static inline var mins = 33; // vec3
    @f static inline var mins1 = 34;
    @f static inline var mins2 = 35;
    @f static inline var maxs = 36; // vec3
    @f static inline var maxs1 = 37;
    @f static inline var maxs2 = 38;
    @f static inline var size = 39; // vec3
    @f static inline var size1 = 40;
    @f static inline var size2 = 41;
    @i static inline var touch = 42; // func
    @i static inline var use = 43; // func
    @i static inline var think = 44; // func
    @i static inline var blocked = 45; // func
    @f static inline var nextthink = 46; // float
    @i static inline var groundentity = 47; // edict
    @f static inline var health = 48; // float
    @f static inline var frags = 49; // float
    @f static inline var weapon = 50; // float
    @i static inline var weaponmodel = 51; // string
    @f static inline var weaponframe = 52; // float
    @f static inline var currentammo = 53; // float
    @f static inline var ammo_shells = 54; // float
    @f static inline var ammo_nails = 55; // float
    @f static inline var ammo_rockets = 56; // float
    @f static inline var ammo_cells = 57; // float
    @f static inline var items = 58; // float
    @f static inline var takedamage = 59; // float
    @i static inline var chain = 60; // edict
    @f static inline var deadflag = 61; // float
    @f static inline var view_ofs = 62; // vec3
    @f static inline var view_ofs1 = 63;
    @f static inline var view_ofs2 = 64;
    @f static inline var button0 = 65; // float
    @f static inline var button1 = 66; // float
    @f static inline var button2 = 67; // float
    @f static inline var impulse = 68; // float
    @f static inline var fixangle = 69; // float
    @f static inline var v_angle = 70; // vec3
    @f static inline var v_angle1 = 71;
    @f static inline var v_angle2 = 72;
    @f static inline var idealpitch = 73; // float
    @i static inline var netname = 74; // string
    @i static inline var enemy = 75; // edict
    @f static inline var flags = 76; // float
    @f static inline var colormap = 77; // float
    @f static inline var team = 78; // float
    @f static inline var max_health = 79; // float
    @f static inline var teleport_time = 80; // float
    @f static inline var armortype = 81; // float
    @f static inline var armorvalue = 82; // float
    @f static inline var waterlevel = 83; // float
    @f static inline var watertype = 84; // float
    @f static inline var ideal_yaw = 85; // float
    @f static inline var yaw_speed = 86; // float
    @i static inline var aiment = 87; // edict
    @i static inline var goalentity = 88; // edict
    @f static inline var spawnflags = 89; // float
    @i static inline var target = 90; // string
    @i static inline var targetname = 91; // string
    @f static inline var dmg_take = 92; // float
    @f static inline var dmg_save = 93; // float
    @i static inline var dmg_inflictor = 94; // edict
    @i static inline var owner = 95; // edict
    @f static inline var movedir = 96; // vec3
    @f static inline var movedir1 = 97;
    @f static inline var movedir2 = 98;
    @i static inline var message = 99; // string
    @f static inline var sounds = 100; // float
    @i static inline var noise = 101; // string
    @i static inline var noise1 = 102; // string
    @i static inline var noise2 = 103; // string
    @i static inline var noise3 = 104; // string

    @f static var ammo_shells1 = null;
    @f static var ammo_nails1 = null;
    @f static var ammo_lava_nails = null;
    @f static var ammo_rockets1 = null;
    @f static var ammo_multi_rockets = null;
    @f static var ammo_cells1 = null;
    @f static var ammo_plasma = null;
    @f static var gravity = null;
    @f static var items2 = null;
}
